import Head from 'next/head';
import Services from '../src/components/Services';
import Layout from '../src/components/Layout';
import HomeSection from '@/src/components/Home/HomeSection';
import HomeReviews from '@/src/components/Home/HomeReviews';
import HomeOursite from '@/src/components/Home/HomeOursite';
import HomeContactUs from '@/src/components/Home/HomeContactUs';
import ScrollDown from '@/src/components/ScrollDown';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ScrollDown />
        <HomeSection />
        <Services />
        <HomeOursite />
        <HomeReviews />
        <HomeContactUs />
      </Layout>
    </>
  );
}
